import json
from urllib import request as url_request
from urllib.error import URLError

from flask import Blueprint, g, jsonify

from ..config import Config
from ..db import fetch_all
from ..security import require_auth

ai_bp = Blueprint("ai", __name__)


def post_ai_worker(path: str, payload: dict):
    body = json.dumps(payload, default=str).encode("utf-8")
    request = url_request.Request(
        f"{Config.AI_WORKER_URL}{path}",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with url_request.urlopen(request, timeout=25) as response:
        return json.loads(response.read().decode("utf-8"))


def fallback_insights(expenses, budgets, investments, goals):
    top_category = expenses[0]["category"] if expenses else "discretionary spending"
    sip_total = sum(float(row["monthly_sip"]) for row in investments)
    top_goal = goals[0]["title"] if goals else "your highest-priority goal"
    return [
        {
            "id": "ai-1",
            "title": f"Review {top_category} spend velocity",
            "body": "Your highest spend category deserves a weekly guardrail. Set a fixed cap and move surplus into savings before the weekend.",
            "impact": "Improves budget discipline this month",
            "priority": "High",
        },
        {
            "id": "ai-2",
            "title": "Automate savings before expenses",
            "body": "Shift savings to the start of the month. Treat it like a bill so discretionary decisions happen after wealth-building is funded.",
            "impact": "Raises savings consistency",
            "priority": "Medium",
        },
        {
            "id": "ai-3",
            "title": f"Fund {top_goal} before upgrades",
            "body": f"Current tracked SIP is {sip_total:,.0f}. Keep investments steady, then direct extra surplus toward your highest-priority goal.",
            "impact": "Balances liquidity and long-term compounding",
            "priority": "Medium",
        },
    ]


@ai_bp.get("/insights")
@require_auth
def insights():
    expenses = fetch_all(
        """
        select c.name as category, e.merchant, e.amount, e.spent_at
        from expenses e
        join categories c on c.id = e.category_id
        where e.user_id = %s
        order by e.amount desc
        limit 12
        """,
        (g.user_id,),
    )
    budgets = fetch_all(
        """
        select c.name as category, b.monthly_limit
        from budgets b
        join categories c on c.id = b.category_id
        where b.user_id = %s
        order by c.name
        """,
        (g.user_id,),
    )
    investments = fetch_all(
        """
        select asset, kind, current_value, monthly_sip, goal
        from investments
        where user_id = %s
        order by current_value desc
        """,
        (g.user_id,),
    )
    goals = fetch_all(
        """
        select title, target_amount, current_amount, deadline, priority
        from goals
        where user_id = %s
        order by case priority when 'High' then 1 when 'Medium' then 2 else 3 end, deadline asc
        """,
        (g.user_id,),
    )

    try:
        worker_response = post_ai_worker(
            "/budget-advice",
            {"expenses": expenses, "budgets": budgets, "investments": investments, "goals": goals},
        )
        text = str(worker_response.get("result", ""))
        normalized = [
            {
                "id": "ollama-1",
                "title": "Local AI budget advisor",
                "body": text[:650] or "The local AI worker returned an empty response.",
                "impact": "Generated by local Ollama RAG pipeline",
                "priority": "Medium",
            }
        ]
    except (URLError, TimeoutError, json.JSONDecodeError):
        normalized = fallback_insights(expenses, budgets, investments, goals)

    return jsonify({"insights": normalized, "source": "ollama-or-rules"})


@ai_bp.post("/chat")
@require_auth
def chat():
    payload = {
        "expenses": [],
        "budgets": [],
        "investments": [],
        "goals": [],
        "question": "How can I improve my financial health this week?",
    }
    try:
        worker_response = post_ai_worker("/chat", payload)
        return jsonify(worker_response)
    except (URLError, TimeoutError, json.JSONDecodeError):
        return jsonify({"result": "AI worker is offline. Start Ollama and apps/ai-worker, then try again.", "source": "fallback"}), 503
